name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: write
  pages: write

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm install --immutable

      - name: Build Docusaurus website
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages

      - name: Notify Slack on success
        if: success()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{
            "text": ":rocket: Docusaurus 사이트가 성공적으로 배포되었습니다.\n<https://your-site-url.com|사이트 바로가기>",
            "username": "Docusaurus Bot",
            "icon_emoji": ":docusaurus:"
          }' ${{ secrets.SLACK_WEBHOOK_URL }}
          
      - name: Notify Slack on failure
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{
            "text": ":x: Docusaurus 배포가 **실패**했습니다.\n<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|로그 보기>",
            "username": "Docusaurus Bot",
            "icon_emoji": ":warning:"
          }' ${{ secrets.SLACK_WEBHOOK_URL }}